//
// Generated file, do not edit! Created by opp_msgc 4.4 from report.msg.
//

#ifndef _REPORT_M_H_
#define _REPORT_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0404
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include <unordered_map>
#include "types.h"
typedef std::unordered_map<VideoSegment, std::size_t> Stats;
// }}



/**
 * Class generated from <tt>report.msg</tt> by opp_msgc.
 * <pre>
 * packet Report {
 *        ipaddr src = 0;
 *        ipaddr dst = 0;
 *        Stats stats;
 * }
 * </pre>
 */
class Report : public ::cPacket
{
  protected:
    ipaddr src_var;
    ipaddr dst_var;
    Stats stats_var;

  private:
    void copy(const Report& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Report&);

  public:
    Report(const char *name=NULL, int kind=0);
    Report(const Report& other);
    virtual ~Report();
    Report& operator=(const Report& other);
    virtual Report *dup() const {return new Report(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual ipaddr& getSrc();
    virtual const ipaddr& getSrc() const {return const_cast<Report*>(this)->getSrc();}
    virtual void setSrc(const ipaddr& src);
    virtual ipaddr& getDst();
    virtual const ipaddr& getDst() const {return const_cast<Report*>(this)->getDst();}
    virtual void setDst(const ipaddr& dst);
    virtual Stats& getStats();
    virtual const Stats& getStats() const {return const_cast<Report*>(this)->getStats();}
    virtual void setStats(const Stats& stats);
};

inline void doPacking(cCommBuffer *b, Report& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, Report& obj) {obj.parsimUnpack(b);}


#endif // _REPORT_M_H_
